<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_9876543212</name>
   <tag></tag>
   <elementGuidId>c01b4c1a-45ac-4cb3-a854-2ee3174fd84b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='datatable-editable']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.even > td.sorting_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ae4240bd-f4ff-4d65-a7d8-ec1a3db2db87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sorting_1</value>
      <webElementGuid>f260241d-ce36-4762-8662-8937b88727f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9876543212</value>
      <webElementGuid>af5750ee-b28f-4dd8-b9f1-5451599d8a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable-editable&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;sorting_1&quot;]</value>
      <webElementGuid>4cbef7b0-cc16-4407-9f68-50d3d8e7bf41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='datatable-editable']/tbody/tr[2]/td</value>
      <webElementGuid>477d5b63-4bcd-4cf7-8086-1fb04019fe6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jalan 2'])[1]/following::td[2]</value>
      <webElementGuid>eff68f0a-b1f4-4cc2-a9e5-8ab1cd3d82ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='warga 2'])[1]/following::td[3]</value>
      <webElementGuid>47538c7c-597c-4d46-8d49-166de7eae63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='create warga'])[1]/preceding::td[2]</value>
      <webElementGuid>a1cfc3f7-9a1d-40e4-9dd4-b694a37c5fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jalan test'])[1]/preceding::td[3]</value>
      <webElementGuid>f97620d4-3183-4c13-8ec2-8ff6c502c97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9876543212']/parent::*</value>
      <webElementGuid>602b5bbf-c02e-4fad-871a-5cc6385307f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>f8f9f217-bc8a-452c-a904-c37f9f52c347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '9876543212' or . = '9876543212')]</value>
      <webElementGuid>2a43b6f1-ca28-40be-8fed-7bc25a2f20e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
