<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal_tgl</name>
   <tag></tag>
   <elementGuidId>769d74df-2753-45b5-a5c1-43329f63bfcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05468475-f6b2-4c8d-88ae-ec52c4668457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d096a646-0f1a-4773-ad72-9d31428fa450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-mask</name>
      <type>Main</type>
      <value>99/99/9999</value>
      <webElementGuid>7227db66-efc0-4c6a-98be-dfffe80e8bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__/__/____</value>
      <webElementGuid>6bacdbc5-63a6-42a0-8ee1-086674359eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3165eb2c-5a6e-4feb-84e4-6cf60fcca780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl</value>
      <webElementGuid>c02aca30-8f51-40c9-be8d-02f56c063a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date&quot;)</value>
      <webElementGuid>40cea7c7-af7f-4362-8141-c3e437b314e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date']</value>
      <webElementGuid>26a03c7c-5299-4f40-bd9a-db43f2de2346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[3]/div/input</value>
      <webElementGuid>993afaab-cda9-4c42-b997-e79a01cd3a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>900f425f-09ab-4496-a311-25fa368af7e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date' and @placeholder = '__/__/____' and @name = 'tgl']</value>
      <webElementGuid>e2b150ff-812d-452d-9f41-baf4718f40b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
