<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin</name>
   <tag></tag>
   <elementGuidId>1f8186b9-83e4-4dbd-a610-2ea3e7a952fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd2d2502-c2d2-4c41-b959-0805109b9cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link btn btn-success</value>
      <webElementGuid>d23839d2-1e54-4c78-95e7-36687de224ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>508c8cb5-a7e6-4db0-be9c-76ad2724f9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>c14eb8a0-2654-42f7-92c5-91e364dc0742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarTogglerDemo01&quot;)/ul[@class=&quot;navbar-nav ml-auto align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link btn btn-success&quot;]</value>
      <webElementGuid>d22694d4-0a41-486c-a29e-56371e029771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      <webElementGuid>05548813-4440-464b-a871-8bde57bf3c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin')]</value>
      <webElementGuid>394b9f8e-eee8-4e4b-a3da-687e6e0899da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info/Pengumuman'])[1]/following::a[1]</value>
      <webElementGuid>57a5ca6a-677e-42f2-bebb-c8113486fc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Warga'])[1]/following::a[2]</value>
      <webElementGuid>d6a82115-1470-451d-b846-14a59f218b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa mlajah'])[1]/preceding::a[1]</value>
      <webElementGuid>4db9d130-db3f-42c2-9328-c269f155808d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan Bangkalan'])[1]/preceding::a[1]</value>
      <webElementGuid>dfdd75aa-87ec-4be4-8757-31a5c1b6158f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>305b3025-4c7e-4cc6-8d0d-653779204fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin')]</value>
      <webElementGuid>44f6f879-c05d-40eb-9136-904fcb1b0dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>9065c9dd-496b-4ced-b301-e917230308a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>aa328fac-f554-4518-a6af-e532f5a672ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
