<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_deskripsi</name>
   <tag></tag>
   <elementGuidId>039a84b7-54c3-40a0-b1a9-ef94e5d7ebe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editDeskripsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editDeskripsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>15461868-9db3-464f-984a-af914458fa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>67f6eb62-7edd-4f3f-bd59-3988a9379954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>878d44e1-eb8c-48fa-9020-7a5ff6440424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2c07bdb4-55a2-483b-a79a-c418f96e0aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editDeskripsi</value>
      <webElementGuid>1873d5a4-7840-4536-a867-abe4f792838d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/textarea[@id=&quot;editDeskripsi&quot;]</value>
      <webElementGuid>fc367db3-68ee-4c98-ac49-2bc5aa0201a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editDeskripsi']</value>
      <webElementGuid>98131e2a-289e-4a08-ad6c-dd66be0c6ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[2]/div/textarea</value>
      <webElementGuid>3a73b908-de56-45c9-82f0-f233eb7c20b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ce3a8190-155b-47c5-bd81-3fc64c8e84d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'deskripsi' and @id = 'editDeskripsi']</value>
      <webElementGuid>35187005-794a-405f-a420-0ee39bf00de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
