<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tambah Surat_fa fa-plus</name>
   <tag></tag>
   <elementGuidId>17189ea0-fb34-490e-8811-819a011c7a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3f7e5f20-e656-4c56-b861-e1cc29ae8268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>4725fba0-967b-4f0b-85eb-a185ae91a40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fixed js flexbox flexboxlegacy csstransforms csstransforms3d no-overflowscrolling no-mobile-device custom-scroll&quot;]/body[1]/section[@class=&quot;body&quot;]/div[@class=&quot;inner-wrapper&quot;]/section[@class=&quot;content-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg&quot;]/section[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;mb-md&quot;]/a[@class=&quot;modal-with-move-anim btn btn-primary&quot;]/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>37f637ef-bf40-4d76-b36d-46fa9bc2bbdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/i</value>
      <webElementGuid>cde8c8a9-5f17-4a4e-91e8-4d4eaa33fbdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
