<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Perihal_perihal (1)</name>
   <tag></tag>
   <elementGuidId>f4c4028d-4c22-4757-8125-bbd32ce848ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editPerihal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editPerihal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ec5d1f1-1d02-4091-a59d-82559e11320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34383bf8-a5db-4784-91e0-e22edc83968a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>perihal</value>
      <webElementGuid>065beb34-bbd0-4a28-8bea-ef8228d53ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b86ba314-d465-49ba-a08a-bdc6da2f89e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editPerihal</value>
      <webElementGuid>99031063-c583-47f4-82c5-ee0c976dfe84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a84892a-c5d6-4453-be1e-c9daf6c752c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editPerihal&quot;)</value>
      <webElementGuid>4372e5c0-d7c4-45a8-af16-1118d65afa00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editPerihal']</value>
      <webElementGuid>02fd5de3-e65e-4d57-8831-f609e4ead85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[2]/div/input</value>
      <webElementGuid>936222cc-7ce3-4a30-a1d0-f421b9012ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9ed7917a-a2b4-46d1-9cb6-79e880fed898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'perihal' and @id = 'editPerihal']</value>
      <webElementGuid>74fbfcc1-4630-4408-8b3b-8cb9626f638f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
