<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Judul_judul (3)</name>
   <tag></tag>
   <elementGuidId>eb914aaa-36c7-4d0c-9f8c-764462cd2496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editJudul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editJudul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd6ed391-6836-46a8-b52f-67b5984d667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b0c1fed-381a-47bd-9013-35f97f3bc05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>db3b4cb3-7952-4f51-a06b-8af289369718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8db371e-bd66-4766-838f-fad6eb105d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editJudul</value>
      <webElementGuid>d60cbeed-2052-493d-bb6f-a4245cd2c96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editJudul&quot;)</value>
      <webElementGuid>4061964b-c204-40f6-a1fb-e3d12383d0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editJudul']</value>
      <webElementGuid>a009b5fb-d811-492c-a2a9-78f78977bafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div/div/input</value>
      <webElementGuid>6149c45c-3e77-4c4f-b8ea-2491ef31d56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4dfcd287-ba06-467a-8e86-bdb482c86183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'judul' and @id = 'editJudul']</value>
      <webElementGuid>f9ec9061-e104-4fb5-942b-1efded5af329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
