<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Judul_judul (5)</name>
   <tag></tag>
   <elementGuidId>b55302b5-7a20-488e-a074-d3654ad3cb82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editJudul</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editJudul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93090727-9ef3-4856-af8f-85182e1695f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b69f81b1-d6d0-46c6-9608-1d7d0a9f584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>0fffcf5d-d3cf-4396-a851-5de9dcec99c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c70b6345-b419-4a38-a1fb-d13e5905a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editJudul</value>
      <webElementGuid>c3fb1c89-dcf7-49d5-b6d0-2c8b9a310a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editJudul&quot;)</value>
      <webElementGuid>d48a3ec9-bb62-488f-858e-5a5d924ff6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editJudul']</value>
      <webElementGuid>123f0323-91e2-4660-83ae-6a931d20d739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div/div/input</value>
      <webElementGuid>ae46ccbb-b4aa-4233-8d25-7ac04e143996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>aad47024-d8eb-4fe5-b0bd-4dca0e731908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'judul' and @id = 'editJudul']</value>
      <webElementGuid>86a80ca3-d262-44e0-9c49-fbb479c559cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
