<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi_deskripsi</name>
   <tag></tag>
   <elementGuidId>55329153-7227-4747-946a-7e7367ffa519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editDeskripsi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='editDeskripsi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0916c627-fafa-407f-a4e8-231c544df499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d75bb2b-9ae3-4c20-943e-ea112a83f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deskripsi</value>
      <webElementGuid>7cf45472-8749-488b-a42f-dca71222a33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>284d7eb6-1b9a-4f1b-88b6-47ea34974f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editDeskripsi</value>
      <webElementGuid>1b4bd934-6eec-467d-b0a5-dce603f7da1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-form&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/textarea[@id=&quot;editDeskripsi&quot;]</value>
      <webElementGuid>06f35ff4-1d4f-4239-bc0e-55c0b4b5f734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='editDeskripsi']</value>
      <webElementGuid>24a4bc03-c2db-4b51-be93-129010969c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[2]/div/textarea</value>
      <webElementGuid>08d80c61-61b5-4dcf-8605-90c1120f8dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>21d6e2ca-0ee4-4431-a8b1-a599802980ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'deskripsi' and @id = 'editDeskripsi']</value>
      <webElementGuid>e1685a19-6fe2-4b07-9675-a56b62bf219c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
