<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tambah Surat_fa fa-plus</name>
   <tag></tag>
   <elementGuidId>5f9d2697-4467-40d5-ac5f-ee27f7e84b85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4b778193-280f-41c9-8314-3c06c56a404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>090103eb-12c9-4be1-82b1-e220a6cae468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fixed js flexbox flexboxlegacy csstransforms csstransforms3d no-overflowscrolling no-mobile-device custom-scroll&quot;]/body[1]/section[@class=&quot;body&quot;]/div[@class=&quot;inner-wrapper&quot;]/section[@class=&quot;content-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg&quot;]/section[@class=&quot;panel&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6&quot;]/div[@class=&quot;mb-md&quot;]/a[@class=&quot;modal-with-move-anim btn btn-primary&quot;]/i[@class=&quot;fa fa-plus&quot;]</value>
      <webElementGuid>ff716f31-ec50-413f-8c9f-c00c79f4ddd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/i</value>
      <webElementGuid>abc040f0-e222-4032-aded-c027b6918a8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
