<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal_asal (3)</name>
   <tag></tag>
   <elementGuidId>c6a48e43-4d42-449e-b60c-bddd5a12529d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#editAsal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='editAsal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe4789d6-36dc-400d-ab54-0c08d5dd6554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62a5ff45-e871-4224-8d3b-d4e743811e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal</value>
      <webElementGuid>db86f948-e6a0-4961-9081-e2430858635c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e2ec6558-00f4-4f01-acf1-39484082525d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editAsal</value>
      <webElementGuid>777f07b8-3a47-43a5-807a-c1b972674061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a66e963-6d01-408d-9ee6-57125cde4e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;editAsal&quot;)</value>
      <webElementGuid>618b2524-bd6f-447b-9464-bed8b9f506ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='editAsal']</value>
      <webElementGuid>10133295-b94c-48c8-8ab2-6d624ce07fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[4]/div/input</value>
      <webElementGuid>6247cdb2-d3fe-4184-9c0c-8ee18523708a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>66bc3744-0c11-4687-a258-964cbaf3ac90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'asal' and @id = 'editAsal']</value>
      <webElementGuid>3fd9254f-2502-4cc6-bc15-9baadf16b949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
