<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal_tgl</name>
   <tag></tag>
   <elementGuidId>52579544-a453-46c9-8d50-4bcb6ee91031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ab09805-2360-44f5-909c-c35e014c9cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>5e71eecb-ccf5-4df2-898c-07379697c2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-mask</name>
      <type>Main</type>
      <value>99/99/9999</value>
      <webElementGuid>fd9ea8b8-c13e-4a28-9d96-d11e3ae5ad80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__/__/____</value>
      <webElementGuid>006e1bf0-30ec-49c0-9b8a-3bbe7d2ecb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a811cc82-b6dd-4846-810f-b695df040d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tgl</value>
      <webElementGuid>f22ef449-5946-42e2-a751-73e043e3a4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date&quot;)</value>
      <webElementGuid>8f579f66-05d3-48bf-94b8-f059d563d991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='date']</value>
      <webElementGuid>86eb9009-f21a-49fc-b2ab-9c3a9f2e52f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div[3]/div/input</value>
      <webElementGuid>ec44e6f8-d8d8-4e27-a9a2-0228b77aa346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>312c8149-7817-426c-b391-fc43e736e7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'date' and @placeholder = '__/__/____' and @name = 'tgl']</value>
      <webElementGuid>74968209-1de7-4700-b0aa-806263da3268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
