<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Surat_noSurat</name>
   <tag></tag>
   <elementGuidId>a1805847-f94d-4c60-97eb-19d0dbd4e037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;noSurat&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='noSurat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8af8ba16-a443-4f5c-bf0d-b1e4d5fbd56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4f1232a-ee4b-4205-b847-97658fead38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>noSurat</value>
      <webElementGuid>ec8f355d-4123-4c36-bf82-2572b60b2658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>993f7803-1f06-4563-b0a6-dbdba13310a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>e1368fb1-24a1-4995-a6ee-39e5a982b98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-form&quot;)/div[@class=&quot;form-group mt-lg&quot;]/div[@class=&quot;col-sm-9&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1710cf53-61a6-40d6-b1fc-1e8cda0ae674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='noSurat']</value>
      <webElementGuid>dffbcfd6-ba10-4d9d-a08a-1fcc31fa6b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demo-form']/div/div/input</value>
      <webElementGuid>79333e06-59cf-4472-873b-075293d3a711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>b8ac355a-2790-453b-a8e8-cc2e03b43383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'noSurat']</value>
      <webElementGuid>f90d51e4-db9a-4ba0-946c-beb60f66ac72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
