<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin (8)</name>
   <tag></tag>
   <elementGuidId>92826924-d0eb-48a1-ae7e-cdc26a4db7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>71f33510-6e45-4a58-8f57-ef09fed8137f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link btn btn-success</value>
      <webElementGuid>b92ab85d-b8c9-4c8e-bf0a-5f233efa5224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>644ef879-616f-4e51-b423-4202147888af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>17e657cd-ec06-4e63-af6a-552945d73649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarTogglerDemo01&quot;)/ul[@class=&quot;navbar-nav ml-auto align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link btn btn-success&quot;]</value>
      <webElementGuid>6ad7e98d-3770-4a88-b3f5-d66e34c33a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      <webElementGuid>f1f92b0e-962a-4a48-bfe1-974e4b2f34c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin')]</value>
      <webElementGuid>e9e9c7d4-2cb7-455e-9e8c-45c49b00d49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info/Pengumuman'])[1]/following::a[1]</value>
      <webElementGuid>1d07a198-8604-49c8-b35b-b3f7f6c8e8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Warga'])[1]/following::a[2]</value>
      <webElementGuid>2d067877-0e2a-4724-aad8-2f26c9ff19f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa mlajah'])[1]/preceding::a[1]</value>
      <webElementGuid>163c6393-c744-450d-8f48-743087d561a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan Bangkalan'])[1]/preceding::a[1]</value>
      <webElementGuid>f1c3fb42-f4ab-49a1-a77d-ec89cda0073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>96a6c248-c036-46f8-b2a6-00a54c123c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin')]</value>
      <webElementGuid>c8ccf14b-5c0a-4ced-b526-4ef3bc25113a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>28afe7d7-1397-4465-9360-54473693a9a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>ca465614-e9cc-401c-9baa-297e24a5811e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
