<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin (12)</name>
   <tag></tag>
   <elementGuidId>f2f64014-dddd-41b0-894a-e97c1aee4bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2a7d9c4-7812-4b5b-8530-87d903821b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link btn btn-success</value>
      <webElementGuid>80249df6-cba4-457c-a6d9-1a80eff1b44b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>dc0c476e-80b5-49ce-b759-7b3a2045947d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>2bb0cc2d-6a6a-4a7f-944f-ee77084a3979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarTogglerDemo01&quot;)/ul[@class=&quot;navbar-nav ml-auto align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link btn btn-success&quot;]</value>
      <webElementGuid>9bcd71e8-d459-4c65-bdf4-25aa8d4e6534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      <webElementGuid>6d3ccecc-ccfb-4a09-bb04-16ff80de9c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin')]</value>
      <webElementGuid>0d20ca1c-07f8-4c06-8eeb-fd0eb4dd9334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info/Pengumuman'])[1]/following::a[1]</value>
      <webElementGuid>64b75964-da60-4a98-8d26-845d59a65291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Warga'])[1]/following::a[2]</value>
      <webElementGuid>e72d3895-7e4b-49f5-9a4f-9e9b9ff03b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa mlajah'])[1]/preceding::a[1]</value>
      <webElementGuid>f18fa06f-1d13-4ac5-a78f-c72630f77720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan Bangkalan'])[1]/preceding::a[1]</value>
      <webElementGuid>80d3c757-59b4-4848-bde1-515bf2efb284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>028bb979-7b37-4595-8e62-ad916704891c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin')]</value>
      <webElementGuid>a53da089-0665-4157-a761-a3264d124bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>4cdfe5b4-f3d7-4fa6-9b47-90e2a308d37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>c9f9cf12-eceb-48ff-a632-3abd5c6bda64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
