<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admin (24)</name>
   <tag></tag>
   <elementGuidId>6fd0b312-2d2f-4c51-ae85-a1f9a71c6cba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8cc4fc4-1ad8-4d89-9dcc-bdf39541f550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link btn btn-success</value>
      <webElementGuid>2f1ebdd0-d69a-486f-b410-ba7546fd22f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>admin</value>
      <webElementGuid>4c15c10f-97f2-4353-8b64-51926e6464dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin</value>
      <webElementGuid>df513dde-7b68-436a-ab0d-08a1e61416c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarTogglerDemo01&quot;)/ul[@class=&quot;navbar-nav ml-auto align-items-center&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link btn btn-success&quot;]</value>
      <webElementGuid>87781fef-993d-49ae-b65d-b9c25507d3b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo01']/ul/li[4]/a</value>
      <webElementGuid>0ea7027c-7a20-4d5c-96d4-0258304c4f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Admin')]</value>
      <webElementGuid>10f209ff-8a20-4574-b38e-31b2ff7f455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info/Pengumuman'])[1]/following::a[1]</value>
      <webElementGuid>e832c7c2-7892-457a-b5a8-27a750390fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Warga'])[1]/following::a[2]</value>
      <webElementGuid>55889ef7-6f46-4754-8060-e5021ba4ca86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa mlajah'])[1]/preceding::a[1]</value>
      <webElementGuid>c6172f8b-4477-42ce-a838-e24b3350e576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan Bangkalan'])[1]/preceding::a[1]</value>
      <webElementGuid>445f516c-bbf0-4789-a24a-55ad46bbe625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Admin']/parent::*</value>
      <webElementGuid>e6de56d4-713e-4d1d-b344-4fdc9cc34ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'admin')]</value>
      <webElementGuid>4bd88d91-e243-440c-805f-30ca5f5edc9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>29f9832b-53e9-4f34-810a-e7b0daf5da39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'admin' and (text() = 'Admin' or . = 'Admin')]</value>
      <webElementGuid>48e0f847-6a01-4953-ac63-5d1c0e5d4531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
